### ISSUE TITLE
Problem with "empty parameters" and shinken

### ISSUE THREAD

**Issue by algorys** [ddurieux/glpi_monitoring#158]
Hello @ddurieux ,

I'll be posting here following the bug reported last Thursday : https://github.com/naparuba/shinken/issues/1604

Here is the output of Shinken : 

[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R10ProCurveSwitch2510B-24/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R11Switch420024ports1010010003COM/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R12Switch420024ports1010010003COM/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R13Switch24ports1000HPProCurve1800-24G/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R14Switch24ports1000HPProCurve1810G-24J9450A/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R15Switch24ports1000HPProCurve1810G-24/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R17-R18SwitchCiscostack/CheckSwitch
[1430401882] INFO: [Shinken] [GLPI Arbiter] New service: R19Switch24portsHPProCurve1810-24GJ9803A/CheckSwitch
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Got 0 contacts
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 38 commands to Arbiter
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 9 hosts to Arbiter
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 1 hosts groups to Arbiter
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 1 services templates to Arbiter
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 8 services to Arbiter
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 3 timeperiods to Arbiter
[1430401882] WARNING: [Shinken] [GLPI Arbiter] Sending 0 contacts to Arbiter
[1430401882] INFO: [Shinken] [GLPI Arbiter] Sending all data to Arbiter
[1430401882] CRITICAL: [Shinken] I got an unrecoverable error. I have to exit.
[1430401882] CRITICAL: [Shinken] You can get help at https://github.com/naparuba/shinken
[1430401882] CRITICAL: [Shinken] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1430401882] CRITICAL: [Shinken] Back trace of the error: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 595, in main
self.load_config_file()
File "/usr/local/lib/python2.7/dist-packages/shinken/daemons/arbiterdaemon.py", line 370, in load_config_file
self.conf.create_objects(raw_objects)
File "/usr/local/lib/python2.7/dist-packages/shinken/objects/config.py", line 1083, in create_objects
self.create_objects_for_type(raw_objects, t)
File "/usr/local/lib/python2.7/dist-packages/shinken/objects/config.py", line 1102, in create_objects_for_type
o = cls(obj_cfg)
File "/usr/local/lib/python2.7/dist-packages/shinken/objects/item.py", line 97, in init
val = self.properties[key].pythonize(params[key])
File "/usr/local/lib/python2.7/dist-packages/shinken/property.py", line 181, in pythonize
return to_int(val)
File "/usr/local/lib/python2.7/dist-packages/shinken/util.py", line 233, in to_int
return int(float(val))
ValueError: could not convert string to float:

And the cfg (those who seem concerned) generate by the getconfig.php : 

command.cfg --> http://pastebin.com/KWmLnuLN
hosts.cfg --> http://pastebin.com/S4U17sXk

The others are empty or seems not be "incriminate".

If you want more information I can give you.
For now, Shinken only restart with plugin but no hosts are added and tables too...

I have Shinken 2.4 (the bug is initial on 2.2).
GLPI 0.84.8
Monitoring 0.84+1.3g
Services Web 1.4.3

Thanks for help in advance.

**Comment by ddurieux** [comment]
Go in root entity form, tab monitoring, and select a component and save

**Comment by algorys** [comment]
Yes, he says Success to modify

**Comment by ddurieux** [comment]
When you start again shinken, it works?

**Comment by algorys** [comment]
Yes it works, and the initial catalog's problem works too. Thanks @ddurieux ...

A few question, 

Why I had to go to root entity to solve this ?
The bug appears suddenly, is it normal ?
Is there a gabarit for multiple check port of switch ?

**Comment by ddurieux** [comment]
I think the problem come with the delete commands if you delete the command use in entity form.

The use of command in entity is used to use a command on host to see if the host is alive

**Comment by algorys** [comment]
Ok I understand. So I'll delete commands with precaution next time. ^^

I have some problem with IP resolution, but it seems works. I close issue. Many thanks.
